version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.9.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
- package-ecosystem: bundler
  directory: "/my_api"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
- package-ecosystem: bundler
  directory: "/rails_app/rails_7.2"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
- package-ecosystem: github-actions
  directory: "/rails_app/rails_7.2"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
- package-ecosystem: bundler
  directory: "/rails_app/rails_8.0"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
- package-ecosystem: github-actions
  directory: "/rails_app/rails_8.0"
  schedule:
    interval: weekly
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
- package-ecosystem: bundler
  directory: "/rails_app/rails_8.1"
  schedule:
    interval: weekly
    day: monday
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
- package-ecosystem: github-actions
  directory: "/rails_app/rails_8.1"
  schedule:
    interval: weekly
    day: monday
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
