version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.9.0
- package-ecosystem: bundler
  directory: "/my_api"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  assignees:
  - ryz310
  labels:
  - dependabot
